import { useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";

import Skeleton from "@shared/ui/composites/Skeleton.jsx";
import EmptyState from "@shared/ui/composites/EmptyState.jsx";

import { useInvoice } from "@proshop/invoices/api/invoices.queries.js";
import { formatMoney } from "@shared/lib/money.js";
import { formatDate } from "@shared/lib/dates.js";

import styles from "../styles/invoices.module.css";

export default function InvoicePrintPage() {
  const { id } = useParams();
  const nav = useNavigate();
  const { data: invoice, isLoading } = useInvoice(id);

  useEffect(() => {
    if (!invoice) return;
    const t = setTimeout(() => window.print(), 250);
    return () => clearTimeout(t);
  }, [invoice]);

  if (isLoading) return <Skeleton rows={6} />;
  if (!invoice) {
    return (
      <EmptyState
        title="Invoice not found"
        description="The requested invoice does not exist or was removed."
        actionLabel="Back"
        onAction={() => nav(-1)}
      />
    );
  }

  return (
    <div className={styles.printPage}>
      <div className={styles.printHeader}>
        <div>
          <div className={styles.printTitle}>Invoice</div>
          <div className={styles.printSub}>#{invoice.id.slice(0, 8)}</div>
        </div>
        <div className={styles.printMeta}>
          <div>Date: {formatDate(invoice.createdAt)}</div>
          <div>Status: {invoice.status}</div>
        </div>
      </div>

      <div className={styles.printGrid}>
        <div>
          <div className={styles.printSectionTitle}>Customer</div>
          <div className={styles.printBox}>
            <div>{invoice.userName || "—"}</div>
            <div className={styles.muted}>{invoice.userEmail || "—"}</div>
          </div>
        </div>
        <div>
          <div className={styles.printSectionTitle}>Transaction</div>
          <div className={styles.printBox}>
            <div>Type: {invoice.type}</div>
            {invoice.duration ? <div>Duration: {invoice.duration} days</div> : null}
          </div>
        </div>
      </div>

      <div className={styles.printSectionTitle}>Line Items</div>
      <table className={styles.printTable}>
        <thead>
          <tr>
            <th>Item</th>
            <th>Qty</th>
            <th>Unit</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {(invoice.lines || []).map((l, idx) => (
            <tr key={idx}>
              <td>
                <div>{l.name}</div>
                <div className={styles.muted}>{l.sku}</div>
              </td>
              <td>{l.quantity}</td>
              <td>{formatMoney(l.unitPriceCents)}</td>
              <td>{formatMoney(l.lineTotalCents)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className={styles.printTotals}>
        <div className={styles.totalRow}>
          <span>Subtotal</span>
          <strong>{formatMoney(invoice.subtotalCents)}</strong>
        </div>
        <div className={styles.totalRow}>
          <span>Tax</span>
          <strong>{formatMoney(invoice.taxCents)}</strong>
        </div>
        <div className={styles.totalRow}>
          <span>Total</span>
          <strong>{formatMoney(invoice.totalCents)}</strong>
        </div>
      </div>

      <div className={styles.printFooter}>
        Generated by ProShop Admin
      </div>
    </div>
  );
}
